name: hashicorp-stack

services:
  # HashiCorp Vault for secrets management
  hc-vault:
    image: hashicorp/vault:1.15
    container_name: hc-vault
    ports:
      - "8200:8200"  # Standard Vault port
    volumes:
      - vault_data:/vault/data
    cap_add:
      - IPC_LOCK
    command: server -dev
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    restart: on-failure
    networks:
      nomad_network:
        ipv4_address: 172.28.0.2
      monitoring_network:

  # HashiCorp Consul for service discovery and configuration
  hc-consul:
    image: hashicorp/consul:1.15
    container_name: hc-consul
    ports:
      - "8500:8500"  # HTTP API and UI on standard port
      - "8600:8600/tcp"  # DNS interface (TCP) on standard port
      - "8600:8600/udp"  # DNS interface (UDP) on standard port
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data
    command: agent -dev -client=0.0.0.0
    restart: on-failure
    networks:
      nomad_network:
        ipv4_address: 172.28.0.3
      monitoring_network:

volumes:
  vault_data:
  vault_logs:

networks:
  nomad_network:
    name: nomad_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
  monitoring_network:
    external: true
    name: prometheus_monitoring_network 