version: '3'

includes:
  docker: 
    taskfile: ./docker/Taskfile.yml
    dir: ./docker
  nomad: 
    taskfile: ./nomad/Taskfile.yml
    dir: ./nomad
  dns: 
    taskfile: ./dnsmasq/Taskfile.yml
    dir: ./dnsmasq
  consul: 
    taskfile: ./consul/Taskfile.yml
    dir: ./consul
  ras: 
    taskfile: ./ras/Taskfile.yml
    dir: ./ras

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task --list
    silent: true
