version: '3'

includes:
  docker: ./docker/Taskfile.yml
  nomad: ./nomad/Taskfile.yml
  dns: ./dnsmasq/Taskfile.yml
  consul: ./consul/Taskfile.yml
  ras: ./ras/Taskfile.yml

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task --list
    silent: true
