global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
      
  - job_name: 'node_exporter_mac'
    static_configs:
      - targets: ['host.docker.internal:9100']
      
  - job_name: 'nodejs_app'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'nodejs-app'
          environment: 'development'
          
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'dev-proxy'
          environment: 'development' 