global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Core services
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
      
  - job_name: 'node_exporter_mac'
    static_configs:
      - targets: ['host.docker.internal:9100']
  
  # Database monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
      
  # General Nginx metrics
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'dev-proxy'
          environment: 'development'
          app: 'general'
          
  # Include application-specific configurations
  - job_name: 'file_sd_apps'
    file_sd_configs:
      - files:
        - /etc/prometheus/conf.d/*.yml
        refresh_interval: 5s
