global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
      
  - job_name: 'node_exporter_mac'
    static_configs:
      - targets: ['host.docker.internal:9100']
      
  - job_name: 'nodejs_app'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'nodejs-app'
          environment: 'development'
          
  # General Nginx metrics for the proxy server overall
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'dev-proxy'
          environment: 'development'
          app: 'general'

  # Specific metrics for the Node.js application
  - job_name: 'nodejs_proxy'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodejs-exporter:9113']
        labels:
          service: 'nodejs-proxy'
          environment: 'development'
          app: 'nodejs'
          port: '3000'




  # Specific metrics for the bb_client application
  - job_name: "bb_client_proxy"
    scrape_interval: 5s
    static_configs:
      - targets: ["bb_client-exporter:9113"]
        labels:
          service: "bb_client-proxy"
          environment: "development"
          app: "bb_client"
          port: "4000"
  # Specific metrics for the Rust application
  - job_name: 'rust_proxy'
    scrape_interval: 5s
    static_configs:
      - targets: ['rust-exporter:9113']
        labels:
          service: 'rust-proxy'
          environment: 'development'
          app: 'rust'
          port: '8000' 