services:
  nodejs-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nodejs-exporter
    ports:
      - "9114:9113"  # Note: externally exposed on a different port
    command:
      - "--nginx.scrape-uri=http://dev-proxy:3000/nodejs_status"
      - "--prometheus.const-label=app=nodejs"
      - "--prometheus.const-label=port=3000"
    networks:
      - monitoring_network
    restart: always 