version: '1.0'

# Model Context Protocol Configuration
models:
  default: gpt-4o
  available:
    - name: gpt-4o
      provider: openai
      context_window: 128000
      max_tokens: 4096
      temperature: 0.7
    - name: claude-3-opus
      provider: anthropic
      context_window: 200000
      max_tokens: 4096
      temperature: 0.7
    - name: claude-3-sonnet
      provider: anthropic
      context_window: 180000
      max_tokens: 4096
      temperature: 0.7

contexts:
  default: general
  available:
    - name: general
      description: "General purpose context for everyday tasks"
      max_tokens: 4000
      priority: 1
    - name: coding
      description: "Context optimized for coding and development tasks"
      max_tokens: 8000
      priority: 2
    - name: system
      description: "System administration and infrastructure context"
      max_tokens: 6000
      priority: 3
    - name: security
      description: "Security and compliance related context"
      max_tokens: 5000
      priority: 4

handlers:
  default: basic
  available:
    - name: basic
      type: direct
      description: "Basic direct interaction with the model"
    - name: chain
      type: sequential
      description: "Chain of thought processing"
    - name: tree
      type: branching
      description: "Tree of thoughts processing"
    - name: agent
      type: autonomous
      description: "Autonomous agent with tools"

prompts:
  default: standard
  available:
    - name: standard
      template: "standard.md"
      description: "Standard interaction template"
    - name: coding
      template: "coding.md"
      description: "Coding focused template"
    - name: system
      template: "system.md"
      description: "System administration template"
    - name: security
      template: "security.md"
      description: "Security focused template"

settings:
  max_retries: 3
  timeout: 60
  cache_enabled: true
  cache_ttl: 3600
  log_level: info
  metrics_enabled: true 