{
 "title": "Remix App Metrics",
 "tags": [
  "remix",
  "proxy",
  "nginx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Remix App Request Rate",
   "type": "timeseries",
   "description": "Remix proxy traffic monitored through Nginx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{job=\"nginx\", service=\"dev-proxy\"}[1m]) * on() group_left() (absent(nginx_up{job=\"nginx\"}) or (nginx_up{job=\"nginx\"}))",
     "legendFormat": "Requests/sec"
    }
   ]
  },
  {
   "title": "Remix App Active Connections",
   "type": "timeseries",
   "description": "Active connections to Remix app",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_active{job=\"nginx\", service=\"dev-proxy\"}",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Total Remix Requests",
   "type": "stat",
   "description": "Total requests to Remix app",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_http_requests_total{job=\"nginx\", service=\"dev-proxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "piechart",
   "description": "Connection statuses for Remix app",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_reading{job=\"nginx\", service=\"dev-proxy\"}",
     "legendFormat": "Reading"
    },
    {
     "expr": "nginx_connections_writing{job=\"nginx\", service=\"dev-proxy\"}",
     "legendFormat": "Writing"
    },
    {
     "expr": "nginx_connections_waiting{job=\"nginx\", service=\"dev-proxy\"}",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Remix App Traffic",
   "type": "timeseries",
   "description": "Traffic to Remix app in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(nginx_http_request_size_bytes_sum{job=\"nginx\", service=\"dev-proxy\"}[1m])",
     "legendFormat": "Bytes sent"
    }
   ]
  }
 ]
}