# Vector configuration for logging with unified port

# Source for collecting logs from Docker
[sources.docker_source]
type = "docker_logs"
docker_host = "unix:///var/run/docker.sock"
auto_partial_merge = true

# Single unified socket source for all application logs
[sources.unified_socket]
type = "socket"
mode = "tcp"
address = "0.0.0.0:45000"

# Output logs to Loki
[sinks.loki]
type = "loki"
inputs = ["docker_source", "unified_socket"]
endpoint = "http://loki:3100"
encoding.codec = "json"
labels.app = "app_logs"
labels.host = "{{ host }}"
labels.source_type = "{{ source_type }}"
